### ISSUE TITLE
Plugin is not recognized as a valid plugin anymore

### ISSUE THREAD

**Issue by serveln** [BatchDrake/APTPlugin#1]
After commit https://github.com/BatchDrake/SigDigger/commit/8c78db655538da68aafba00ec234bfbd8db3219f, the plugin stopped working, and it is not recognized as a valid plugin anymore.

<img width="978" height="245" alt="Image" src="https://github.com/user-attachments/assets/a6af7260-cc4b-42f8-bf36-0e03c1b77226" />

**Comment by BatchDrake** [comment]
My bad, I made changes to the plugin API and forgot to put this one up to
date. I will update it along the day.

Thanks por reporting,

>> Gonzalo José Carracedo Carballal

**Comment by BatchDrake** [comment]
Hi @serveln , I have just updated the code to work with the new plugin API. Tell me if it builds.

**Comment by serveln** [comment]
Hello! Thank you for your fast reply. Sadly it didn't work for me, still not recognized. But the ZeroMQPlugin fix worked perfectly fine.

<img width="1286" height="228" alt="Image" src="https://github.com/user-attachments/assets/467f42f6-6c43-4db5-9fed-ce795898c2f4" />

**Comment by BatchDrake** [comment]
Okay, I've just realized I thought I was answering the ZeroMQ issue. The problem with this one is the same. You'll have a fix tomorrow morning (CET time)

**Comment by BatchDrake** [comment]
Hi @serveln, this should be working now.

**Comment by serveln** [comment]
Now is working. Thanks!
